apiVersion: v1
kind: Pod
metadata:
  name: assert-caddy-ready
spec:
  restartPolicy: Never
  containers:
  - name: assert-caddy
    image: registry.access.redhat.com/ubi9-minimal:latest
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
    command:
    - sh
    - -c
    - "EXPECTED=\"Welcome,\"\nwhile true; do\n  ACTUAL=$(curl -s http://caddy:80)\n\
      \  # check EXPECTED ~= ACTUAL\n  if echo \"$ACTUAL\" | grep -q \"$EXPECTED\"\
      ; then\n    echo \"assertion passed\"\n    exit 0\n  else\n    echo \"assertion\
      \ failed\"\n    echo \"EXPECTED: $EXPECTED\"\n    echo \"ACTUAL: $ACTUAL\"\n\
      \    sleep 5\n  fi\ndone\n"
