apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akpvc1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: akpv1
