apiVersion: v1
kind: Pod
metadata:
  namespace: ndb-cluster
  name: ndb-cluster-testing-pod
  labels:
    uid: 8eaa5eca-7979-11ef-8c0f-00155d052bda
spec:
  restartPolicy: OnFailure
  serviceAccountName: ndb-cluster-testing-pod-sa
  volumes:
    - name: testing-volume
      persistentVolumeClaim:
        claimName: ndb-cluster-storage
  containers:
    - name: testing-pod
      image: eu.foo.io/alpine:secure-tag@sha256:0000000000000000000000000000000000000000000000000000000000000000
      command:
        - sh
        - -c
        - 'echo "Install OpenSSH"; apk add openssh-server curl netcat-openbsd; ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -q -N ""; sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/g" /etc/ssh/sshd_config; echo "root:123456" | chpasswd; /usr/sbin/sshd -D -e -ddd '
      volumeMounts:
        - mountPath: /mnt/tmp
          name: testing-volume
          readOnly: false
      ports:
        - containerPort: 22
          name: tcp22
      resources:
        limits:
          memory: 256Mi
          cpu: 150m
        requests:
          memory: 128Mi
          cpu: 75m
      securityContext:
        runAsGroup: 10001
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 10001
      imagePullPolicy: Always
  securityContext:
    supplementalGroups:
      - 100
    fsGroup: 2000
    runAsUser: 1000
    runAsGroup: 3000
