apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: secure-namespace
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - image: eu.foo.io/busybox:secure-tag@sha256:0000000000000000000000000000000000000000000000000000000000000000
      command:
        - sleep
        - "3600"
      imagePullPolicy: Always
      name: busybox
      securityContext:
        runAsGroup: 10001
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 10001
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 100m
  securityContext:
    supplementalGroups:
      - 100
    fsGroup: 2000
    runAsUser: 1000
    runAsGroup: 3000
