apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner01
  namespace: default
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 200Gi
status: {}
