apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prompvc
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: prompv
