apiVersion: v1
kind: Pod
metadata:
  name: test-docker-no-seccontext
  labels:
    component: ci
spec:
  # Use service account that can deploy to all namespaces
  # serviceAccountName: jenkins
  #securityContext:
    #fsGroup: 1000
    #runAsUser: 1000
  containers:
    - name: docker
      image: eu.foo.io/docker:secure-tag@sha256:0000000000000000000000000000000000000000000000000000000000000000
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
      securityContext:
        runAsUser: 10001
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
        runAsGroup: 10001
        runAsNonRoot: true
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
  securityContext:
    supplementalGroups:
      - 100
    fsGroup: 2000
    runAsUser: 1000
    runAsGroup: 3000
