apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: production
spec:
  containers:
    - name: nginx-name
      image: eu.foo.io/nginx:secure-tag@sha256:0000000000000000000000000000000000000000000000000000000000000000
      securityContext:
        runAsUser: 10001
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
        runAsGroup: 10001
        runAsNonRoot: true
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
  securityContext:
    supplementalGroups:
      - 100
    fsGroup: 2000
    runAsUser: 1000
    runAsGroup: 3000
