# DEPLOYMENT
#
# kubectl create -f .template.yaml
# kubectl get deployments
# kubectl get replicaset
# kubectl get pods
# kubectl get all
# 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: frontend

spec:
  template:
    # Contains the pod definition
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: eu.foo.io/nginx:secure-tag@sha256:0000000000000000000000000000000000000000000000000000000000000000
          securityContext:
            runAsUser: 10001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            runAsGroup: 10001
            runAsNonRoot: true
          resources:
            limits:
              cpu: 100m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
  replicas: 3
  selector:
    matchLabels:
      # See labels for pods
      type: frontend
