import os
import yaml
import csv
import re

# -------------------------------------------------------------------
# CARGA DE FM EXISTENTE
# -------------------------------------------------------------------

def load_feature_dict(csv_file="../resources/mapping_csv/kubernetes_mapping_properties_features.csv"):
    """
    Devuelve un diccionario:
        midle -> row completa del CSV
    donde 'Midle' es la columna con nombres tipo:
        Pod_spec_containers_securityContext_runAsUser
    """
    feature_dict = {}
    with open(csv_file, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            midle = row["Midle"].strip()
            feature_dict[midle] = row
    return feature_dict


def load_kinds_prefix_mapping(file_path: str) -> dict:
    """
    Create a dict {Kind: Prefix} from the CSV generated by mappingUvlCsvK8sOld.py
    Ex:
        {"Pod": "io_k8s_api_core_v1_Pod",
         "Deployment": "io_k8s_api_apps_v1_Deployment", ...}
    """
    mapping = {}
    with open(file_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            kind = row["Kind"].strip()
            prefix = row["Prefix"].strip()
            mapping[kind] = prefix
    return mapping


def normalize_kind(kind: str, kind_map: dict) -> str:
    """
    Normaliza el nombre del kind usando el mapa de prefijos.
    Si no se encuentra, capitaliza por defecto.
    """
    k_lower = kind.lower()
    for k in kind_map.keys():
        if k.lower() == k_lower:
            return k
    return kind.capitalize()


# -------------------------------------------------------------------
# KUBELINTER: PARSEO DE CHECKS Y TEMPLATES
# -------------------------------------------------------------------

def parse_kubelinter_check(path: str) -> dict | None:
    """
    Lee un check de KubeLinter en YAML y devuelve estructura básica:
      {
        id, description, remediation,
        template, params, scope.objectKinds
      }
    """
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not isinstance(data, dict):
        return None

    return {
        "id": data.get("name") or os.path.splitext(os.path.basename(path))[0],
        "description": data.get("description", ""),
        "remediation": data.get("remediation", ""),
        "template": data.get("template", ""),
        "params": data.get("params", {}) or {},
        "scope": (data.get("scope") or {}),
    }


def infer_context_from_scope(scope: dict) -> str:
    """
    De momento, aproximación:
    - DeploymentLike / Workload -> usamos contexto Pod_spec / Pod_spec_containers
    - Si no se sabe, asumimos Pod_spec.
    Esto no determina el Kind UVL directamente, solo el prefijo 'Midle'.
    """
    object_kinds = (scope.get("objectKinds") or {}).get("included", []) \
                   or scope.get("objectKinds", {}).get("objectKinds", []) \
                   or scope.get("objectKinds", [])  # soportar varias variantes

    # KubeLinter suele usar cosas como DeploymentLike, Pod, Service, etc.
    if "DeploymentLike" in object_kinds or "Workload" in object_kinds:
        return "Pod_spec_containers"  # condiciones a nivel de contenedor en PodSpec
    if "Pod" in object_kinds:
        return "Pod_spec"
    if "Service" in object_kinds:
        return "Service_spec"
    # Por defecto:
    return "Pod_spec"


# -------------------------------------------------------------------
# INFERIR CONDICIONES ESTÁTICAS POR TEMPLATE
# -------------------------------------------------------------------

def infer_conditions_from_template(template: str, params: dict, scope: dict):
    """
    Dado el nombre del template y sus params, devuelve lista de condiciones lógicas abstractas:

    Cada condición es una tupla:
        (context_midle_prefix, prop_path, op, value)

    Ejemplo:
        ("Pod_spec_containers", "securityContext.runAsNonRoot", "==", True)
        ("Pod_spec_containers", "securityContext.runAsUser", ">=", 1)
    """
    ctx = infer_context_from_scope(scope)
    conds = []

    # --- Ejemplos de templates "estáticos" soportados inicialmente ---

    if template == "run-as-non-root":
        # No-root: o runAsNonRoot=true o runAsUser>=1
        conds.append((ctx, "securityContext.runAsNonRoot", "==", True))
        conds.append((ctx, "securityContext.runAsUser", ">=", 1))

    elif template in ("privileged-containers", "no-privileged", "privileged"):
        conds.append((ctx, "securityContext.privileged", "!=", True))

    elif template in ("allow-privilege-escalation", "no-allow-privilege-escalation"):
        conds.append((ctx, "securityContext.allowPrivilegeEscalation", "!=", True))

    elif template in ("host-ipc", "disallow-host-ipc"):
        conds.append(("Pod_spec", "hostIPC", "!=", True))

    elif template in ("host-network", "disallow-host-network"):
        conds.append(("Pod_spec", "hostNetwork", "!=", True))

    elif template in ("dangerous-capabilities", "drop-capabilities"):
        # no ALL, no SYS_ADMIN, no NET_ADMIN en capabilities.add
        conds.append((ctx, "securityContext.capabilities.add", "not_contains", "ALL"))
        conds.append((ctx, "securityContext.capabilities.add", "not_contains", "SYS_ADMIN"))
        conds.append((ctx, "securityContext.capabilities.add", "not_contains", "NET_ADMIN"))

    elif template in ("required-replicas", "multiple-replicas"):
        # Param configurable: replicas >= min_replicas (por defecto 2)
        min_replicas = params.get("min_replicas", 2)
        conds.append(("Deployment_spec", "replicas", ">=", min_replicas))

    elif template in ("readiness-probe", "required-readiness-probe"):
        # Simple: readinessProbe no null
        conds.append((ctx, "readinessProbe", "!=", None))

    else:
        # Template aún no soportado → vacía
        pass

    return conds


# -------------------------------------------------------------------
# BÚSQUEDA DE FEATURES REALES EN EL FM
# -------------------------------------------------------------------

def find_feature(context_midle: str, prop_path: str, feature_dict: dict):
    """
    Intenta mapear (context_midle, prop_path) a una fila real del FM.

    context_midle: ej. "Pod_spec_containers"
    prop_path:     "securityContext.runAsNonRoot"

    Estrategia:
      1) Construir clave Midle candidata:
            Pod_spec_containers_securityContext_runAsNonRoot
      2) Si no existe, buscar por contiene prop_key dentro de midle que empiece por context_midle.
    """
    prop_key = prop_path.replace(".", "_")
    candidate_midle = f"{context_midle}_{prop_key}"

    # 1) coincidencia exacta de Midle
    row = feature_dict.get(candidate_midle)
    if row:
        return row

    # 2) búsqueda aproximada
    candidates = []
    for midle, r in feature_dict.items():
        if midle.startswith(context_midle + "_") and prop_key in midle:
            candidates.append(r)

    if not candidates:
        return None

    # Elegimos la más específica (mayor longitud de Midle)
    return max(candidates, key=lambda r: len(r["Midle"]))


# -------------------------------------------------------------------
# CONVERSIÓN DE CONDICIONES → EXPRESIONES UVL
# -------------------------------------------------------------------

def build_uvl_expr(feature_full: str, op: str, val):
    """
    Convierte (feature_full, op, val) en una expresión UVL.
    feature_full: nombre completo del feature, p.ej.:

        Pod.io_k8s_api_core_v1_Pod_spec_containers_securityContext_runAsNonRoot

    Reglas:
      - == True   -> feature
      - == False  -> !feature
      - != True   -> !feature
      - != False  -> feature
      - >= n      -> feature >= n
      - not_contains v (capabilities) -> (feature_StringValue != 'v')
    """
    full_feature = feature_full

    # == 
    if op == "==":
        if isinstance(val, bool):
            return full_feature if val else f"!{full_feature}"
        if val is None:
            return f"{full_feature} == null"
        return f"{full_feature} == '{val}'"

    # !=
    if op == "!=":
        if isinstance(val, bool):
            # Si != true => false deseado => !feature
            # Si != false => true deseado => feature
            return f"!{full_feature}" if val else full_feature
        if val is None:
            return f"{full_feature} != null"
        return f"{full_feature} != '{val}'"

    # >=
    if op == ">=":
        return f"{full_feature} >= {val}"

    # not_contains (especial para capabilities)
    if op == "not_contains":
        # pequeña heurística: suffix StringValue si es capabilities_add
        if full_feature.endswith("capabilities_add"):
            return f"({full_feature}_StringValue != '{val}')"
        return f"({full_feature} != '{val}')"

    # fallback
    return f"{full_feature} {op} '{val}'"


# -------------------------------------------------------------------
# CHECK KUBELINTER → UVL (usa FM real)
# -------------------------------------------------------------------

def kubelinter_check_to_uvl(check: dict, feature_dict: dict, kind_map: dict):
    """
    Convierte un check de KubeLinter a:
        (feature_block_str, constraint_str)
    o None si no se puede mapear.
    """
    cid   = check["id"].replace("-", "_")
    desc  = check.get("description", "").replace("'", " ")
    tmpl  = check["template"]
    scope = check["scope"]
    params = check["params"]

    # 1) inferir condiciones lógicas abstractas
    conds = infer_conditions_from_template(tmpl, params, scope)
    if not conds:
        print(f"  ⚠ Template {tmpl} sin condiciones estáticas mapeables → skip ({cid})")
        return None

    uvl_exprs = []

    for (ctx, prop_path, op, val) in conds:
        row = find_feature(ctx, prop_path, feature_dict)
        if not row:
            print(f"    ⚠ No FM match para Context={ctx}, prop={prop_path}")
            continue

        feature_full = row["Feature"].strip()  # ya lleva prefijo io_k8s_...
        # Decidir "Kind" textual para UVL: usamos la primera parte antes de '_'
        # ejemplo: io_k8s_api_core_v1_Pod_spec_... → Kind = Pod
        midle = row["Midle"]
        # Kind heurístico: primer segmento del Midle antes de '_spec'
        # p.ej. Pod_spec_containers_securityContext_runAsUser -> Pod
        kind_name = midle.split("_", 1)[0]

        full_feature = f"{kind_name}.{feature_full}"
        expr = build_uvl_expr(full_feature, op, val)
        uvl_exprs.append(expr)

    if not uvl_exprs:
        print(f"  ❌ Ninguna condición de {cid} se pudo mapear a FM → skip")
        return None

    # 2) feature block UVL y constraint
    feature_block = f"{cid} {{doc '{desc}', tool 'KubeLinter', category 'Security'}}"
    if len(uvl_exprs) == 1:
        constraint = f"{cid} => {uvl_exprs[0]}"
    else:
        constraint = f"{cid} => " + " & ".join(uvl_exprs)

    return feature_block, constraint


# -------------------------------------------------------------------
# BARRIDO COMPLETO DE UN DIRECTORIO DE CHECKS KUBELINTER
# -------------------------------------------------------------------

def extract_all_kubelinter_checks(checks_root: str,
                                  features_csv: str,
                                  kinds_csv: str):
    feature_dict = load_feature_dict(features_csv)
    kind_map = load_kinds_prefix_mapping(kinds_csv)

    results = []

    for root, _, files in os.walk(checks_root):
        for f in files:
            if not f.endswith(".yaml"):
                continue
            full_path = os.path.join(root, f)
            check = parse_kubelinter_check(full_path)
            if not check:
                continue

            print(f"\nCheck: {check['id']}")
            print(check)

            uv = kubelinter_check_to_uvl(check, feature_dict, kind_map)
            if uv:
                results.append(uv)

    return results


# -------------------------------------------------------------------
# MAIN DEMO
# -------------------------------------------------------------------

if __name__ == "__main__":
    FEATURES_CSV = "../resources/mapping_csv/kubernetes_mapping_properties_features.csv"
    KINDS_CSV    = "../resources/mapping_csv/kubernetes_kinds_versions_detected.csv"
    KUBELINTER_DIR = "../resources/kubelinter_checks"  # ajusta a tu ruta real

    results = extract_all_kubelinter_checks(KUBELINTER_DIR, FEATURES_CSV, KINDS_CSV)

    print("\n\n### KubeLinter → UVL (checks estáticos) ###\n")
    for fb, cons in results:
        print(fb)
        print(cons)
        print("-" * 80)