# extract_polaris_policies.py

import os, yaml, re, json
from collections import defaultdict
import csv
def parse_polaris_check(filepath):
    """
    Parse un check Polaris (YAML o Go-embedded JSON Schema)
    y extrae metadatos relevantes.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        text = f.read()

    # Detectar YAML frontmatter o JSON Schema incrustado
    try:
        data = yaml.safe_load(text)
    except Exception:
        data = None

    # Si está embebido en Go, extraer con regex tipo `{ "schema": ... }`
    if not isinstance(data, dict):
        match = re.search(r'schema:\s*(\{.*\})', text, re.DOTALL)
        if match:
            schema_text = match.group(1)
            data = yaml.safe_load(schema_text)

    if not data:
        return None

    # Polaris usa campos: target, category, schema, successMessage, failureMessage
    check = {
        "id": os.path.basename(filepath).replace(".yaml", ""),
        "target": data.get("target", ""),
        "category": data.get("category", ""),
        "schema": data.get("schema", {}),
        "successMessage": data.get("successMessage", ""),
        "failureMessage": data.get("failureMessage", ""),
    }
    return check


def extract_conditions_from_schema(schema):
    """
    Analiza el JSON Schema del check y produce condiciones tipo UVL.
    """
    conds = []
    if not isinstance(schema, dict):
        return conds

    props = schema.get("properties", {})
    for field, rule in props.items():
        if "not" in rule and "pattern" in rule["not"]:
            conds.append({
                "field": field,
                "operator": "not match",
                "value": rule["not"]["pattern"]
            })
        elif "enum" in rule:
            conds.append({
                "field": field,
                "operator": "in",
                "value": "|".join(map(str, rule["enum"]))
            })
        elif "pattern" in rule:
            conds.append({
                "field": field,
                "operator": "match",
                "value": rule["pattern"]
            })
        elif "type" in rule and "minimum" in rule:
            conds.append({
                "field": field,
                "operator": ">=",
                "value": rule["minimum"]
            })
    return conds


def polaris_policy_to_uvl(check, kind_map):
    """
    Convierte un check Polaris en un bloque UVL compatible.
    """
    tool = "Polaris"
    feature_name = check["id"].replace("-", "_")
    feature_block = f"{feature_name} {{doc '{check['failureMessage']}', tool '{tool}', category '{check['category']}'}}"

    kind = check["target"]
    kind_cap = kind.capitalize()
    prefix = kind_map.get(kind_cap, "io_k8s_api_core_v1")

    conds = extract_conditions_from_schema(check["schema"])
    constraint_parts = []
    for cond in conds:
        feature = f"{prefix}_{cond['field']}"
        op, val = cond["operator"], cond["value"]
        if op == "not match":
            expr = f"!{kind_cap}.{feature} matches '{val}'"
        elif op == "match":
            expr = f"{kind_cap}.{feature} matches '{val}'"
        elif op == "in":
            expr = f"{kind_cap}.{feature} in ({val})"
        elif op == ">=":
            expr = f"{kind_cap}.{feature} >= {val}"
        else:
            expr = f"{kind_cap}.{feature} == '{val}'"
        constraint_parts.append(expr)

    constraint = f"{feature_name} => " + " & ".join(constraint_parts)
    return feature_block, constraint


def extract_all_polaris_checks(path_root, kind_map):
    results = []
    for root, _, files in os.walk(path_root):
        for f in files:
            if f.endswith(".yaml"):
                check = parse_polaris_check(os.path.join(root, f))
                if check:
                    fb, c = polaris_policy_to_uvl(check, kind_map)
                    results.append((fb, c))
    return results

def load_kinds_prefix_mapping(file_path: str) -> dict:
    """
    Create a dict {Kind: Prefix} from the CSV generated by mappingUvlCsvK8sOld.py
    Ex:
        {"Pod": "io_k8s_api_core_v1", "RoleBinding": "io_k8s_api_rbac_v1", ...}
    """
    mapping = {}
    with open(file_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            kind = row["Kind"].strip()
            prefix = row["Prefix"].strip()
            mapping[kind] = prefix
    return mapping

# DEMO USAGE

## ../resources/kyverno_policies_yamls
#field_map = load_feature_dict("../resources/mapping_csv/kubernetes_mapping_properties_features.csv")
#data = parse_rego_policy("../resources/kyverno_policies_yamls/OPA_Policies/SYS_ADMIN_capability.rego")

path_root = "../resources/kyverno_policies_yamls/Polaris-checks"
kind_map = load_kinds_prefix_mapping("../resources/mapping_csv/kubernetes_kinds_versions_detected.csv")


results = extract_all_polaris_checks(path_root, kind_map)
if results:
    print("\nFeature Block:\n", results)
    #print("\nConstraint:\n", constraint)
else:
    print("No valid UVL mapping found.")
print(f"######PRUEBAS")
