# extract_gatekeeper_policies.py

import yaml
import csv
from pathlib import Path
from collections import defaultdict
from gatekeeper_rego_parser import extract_gatekeeper_conditions_from_rego


# ------------------------------------------------------------
# Helpers básicos
# ------------------------------------------------------------
def build_field_map(csv_path):
    field_map =   (list)

    with open(csv_path) as f:
        reader = csv.DictReader(f)

        for row in reader:
            # Ex: Detect feature using the FM mapping
            semantic_key = row["feature_name"]  # p.ej.: securityContext.capabilities.add // We need to take account the rest of the part of the features using the comments Kinds
            field_map[semantic_key].append(row["feature_path"])

    return field_map

def load_kinds_prefix_mapping(file_path: str) -> dict:
    """
    Create a dict {Kind: Prefix} from the CSV generated by mappingUvlCsvK8sOld.py
    Ex:
        {"Pod": "io_k8s_api_core_v1", "RoleBinding": "io_k8s_api_rbac_v1", ...}
    """
    mapping = {}
    with open(file_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            kind = row["Kind"].strip()
            prefix = row["Prefix"].strip()
            mapping[kind] = prefix
    return mapping

def load_feature_dict(csv_file="../resources/mapping_csv/kubernetes_mapping_properties_features.csv"):
    feature_dict = {}

    with open(csv_file, newline='', encoding="utf-8") as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            midle = row["Midle"].strip()
            
            # Almacenar en el diccionario usando 'Midle' como clave
            feature_dict[midle] = row

    return feature_dict

def clean_description(description: str) -> str:
    return description.replace('\n', ' ') \
                      .replace('`', '') \
                      .replace('´', '') \
                      .replace("'", "_") \
                      .replace('{', '') \
                      .replace('}', '') \
                      .replace('"', '') \
                      .replace("\\", "_") \
                      .replace(".", "") \
                      .replace("//", "_").replace('\u2019', '_').replace('\u2018', '_') ## ??''' ¡¡¡ ´´ççç`+++`

def get_base_prefix(kind_prefix): ## Used by the generate_uvl_policies
    if kind_prefix == "Pod":
        return "Pod"
    elif "Replicaset" == kind_prefix:
        return "ReplicaSet"
    elif "Replicationcontroller" == kind_prefix:
        return "RepController"
    elif "Deploymentconfig" == kind_prefix: ## ToDo: More specific str of types if add more kindsQ
        return "DeployConfig" 
    elif "Cronjob" == kind_prefix: ## Added for Rego subtypes
        return "CronJob"
    elif "Serviceaccount" in kind_prefix:
        return "ServAcc"
    elif "Service" in kind_prefix:
        return "Serv"
    elif "Clusterolebinding" in kind_prefix: ## ToDo: More specific str of types if add more kindsQ
        return "ClusRole" 
    elif "Rolebinding" in kind_prefix:
        return "RoleBinding"
    elif "Ingress" in kind_prefix:
        return "Ingress"
    elif "Job" in kind_prefix:
        return "Job"
    elif "Daemonset" in kind_prefix:
        return "DaemonSet"
    elif "Deployment" in kind_prefix:
        return "Deployment"
    elif "Statefulset" in kind_prefix:
        return "StatefulSet"
    elif "Secret" in kind_prefix:
        return "Secret" # PersistentVolumeClaim
    elif "Persistentvolumeclaim" in kind_prefix:
        return "PersistVolumeClaim" ## PodDisruptionBudgetFeatures
    elif "Poddisruptionbudget" in kind_prefix:
        return "PodDisrupBud"
    else:
        return "Kubernetes"

def normalize_rego_path(rego_path):
    # Eliminamos el prefijo 'container.' para que no interfiera con la búsqueda
    if rego_path.startswith("container."):
        return rego_path.replace("container.", "")
    return rego_path

def normalize_kind_name(kind, kind_map):
    """
    Match kind string (rego: lower) to correct official K8s Kind casing.
    Ex: 'cronjob' -> 'CronJob'
    """
    ## kind_prefix_map = load_kinds_prefix_mapping("../resources/mapping_csv/kubernetes_kinds_versions_detected.csv")
    kind_lower = kind.lower()
    for k in kind_map.keys():
        if k.lower() == kind_lower:
            return k  # Return correctly capitalized e.g. CronJob
    return kind.capitalize()

def load_yaml(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    except Exception as e:
        print(f"[ERROR] No se pudo cargar {path}: {e}")
        return None


def sanitize(name: str) -> str:
    return (
        name.replace("-", "_")
            .replace(".", "_")
            .replace("/", "_")
            .replace(" ", "_")
    )


def is_constraint_template(obj: dict) -> bool:
    return isinstance(obj, dict) and obj.get("kind") == "ConstraintTemplate"


def is_constraint(obj: dict) -> bool:
    api = obj.get("apiVersion", "")
    return isinstance(obj, dict) and "constraints.gatekeeper.sh" in api


# ------------------------------------------------------------
# Extracción de REGO desde Templates
# ------------------------------------------------------------

def get_rego_blocks_from_template(template_obj: dict):
    """
    Devuelve una lista de strings con código REGO dentro del ConstraintTemplate.
    Soporta:
    - formato nuevo: spec.targets[].code[].engine: Rego
    - formato viejo: spec.targets[].rego
    """
    regos = []
    spec = template_obj.get("spec", {})
    targets = spec.get("targets", []) or []

    for t in targets:
        # Formato nuevo: code[]
        code_list = t.get("code", [])
        if isinstance(code_list, list):
            for entry in code_list:
                if entry.get("engine") == "Rego":
                    src = entry.get("source", {})
                    rego_txt = src.get("rego")
                    if isinstance(rego_txt, str):
                        regos.append(rego_txt)

        # Formato viejo: target.rego
        if "rego" in t and isinstance(t["rego"], str):
            regos.append(t["rego"])

    return regos

def find_uvl_path_for_rego(kind, rego_path, feature_dict, kind_map): ## feature_dictç
    #print(f"Features dictss {feature_dict}")
    #kind_cap = kind.capitalize()
    real_kind = normalize_kind_name(kind, kind_map)
    #rego_key = rego_path.replace(".", "_")  # container.securityContext.capabilities.add
    rego_key = normalize_rego_path(rego_path).replace(".", "_")

    #print(f"kind    rego    {real_kind}  {rego_key}")
    # Buscar las coincidencias en el diccionario
    candidates = []

    for midle, row in feature_dict.items():
        #print(f"Midel   {midle} {row}")
        if midle.startswith(real_kind + "_") and rego_key in midle:##midle.endswith(rego_key): ## With these conds we take the last match with rego_key, the restrict of is necesary for future cases: In this cases all are similar _asString
            candidates.append(row)
            #print(f"Candidates: {candidates}")
    if not candidates:
        return None, None, None

    # Elegir la más específica (con el mayor número de coincidencias)
    best = max(candidates, key=lambda r: len(r["Midle"]))
    #print(f"Value best  {best}")
    is_list = (best["Value"] == "-")

    return best["Feature"], is_list, best["Value"]

# ------------------------------------------------------------
# Mapear Constraint.kind -> lista de K8s Kinds (Pod, Deployment, ...)
# ------------------------------------------------------------

def build_constraint_kind_map(root_directory: str):
    """
    Recorre todos los constraints.*.yaml del repo y construye:
       { "K8sPSPPrivilegedContainer": ["Pod", ...], ... }
    """
    root = Path(root_directory)
    mapping = {}  # constraintKind -> set(k8sKinds)

    for path in root.rglob("*.yaml"):
        obj = load_yaml(path)
        if not obj or not is_constraint(obj):
            continue

        constraint_kind = obj.get("kind")
        spec = obj.get("spec", {})
        match = spec.get("match", {})
        kinds_block = match.get("kinds", []) or []

        for kentry in kinds_block:
            klist = kentry.get("kinds", []) or []
            for k in klist:
                mapping.setdefault(constraint_kind, set()).add(k)

    return {k: sorted(list(v)) for k, v in mapping.items()}


# ------------------------------------------------------------
# Mapeo Rego → UVL usando tu CSV
# ------------------------------------------------------------

def rego_path_to_search_key(rego_path: str) -> str:
    """
    Convierte rutas como:
        spec.containers[*].securityContext.privileged
    en algo manejable para el buscador de features:
        securityContext.privileged
    (típicamente los últimos 2 segmentos)
    """
    cleaned = rego_path.replace("[*]", "").replace("[]", "")
    parts = cleaned.split(".")
    if len(parts) >= 2:
        sub = ".".join(parts[-2:])  # ej: securityContext.privileged
    else:
        sub = cleaned
    return sub


def build_uvl_expressions_for_template(
    template_name: str,
    rego_blocks,
    k8s_kinds,
    feature_dict,
    kind_map,
):
    """
    A partir de:
    - nombre del template
    - bloques rego
    - lista de K8s kinds (Pod, Deployment, ...)
    - mapping CSV -> features UVL
    genera una lista de expresiones UVL de la forma:
        !Pod.io_k8s_api_core_v1_Pod_spec_containers_securityContext_privileged
    """
    expressions = []

    for rego in rego_blocks:
        paths = extract_gatekeeper_conditions_from_rego(rego)
        if not paths:
            continue

        for k8s_kind in k8s_kinds:
            for p in paths:
                subkey = rego_path_to_search_key(p)
                feature, is_list, value_field = find_uvl_path_for_rego(
                    k8s_kind, subkey, feature_dict, kind_map
                )
                if not feature:
                    print(f"[WARNING] No UVL mapping for path '{p}' (subkey '{subkey}') in kind '{k8s_kind}'")
                    continue

                base_prefix = get_base_prefix(k8s_kind.capitalize())
                # Heurística: si aparece en la condición de violación,
                # significa "si esto es true -> violación", así que el
                # modelo deseable es que sea false:
                expr = f"!{base_prefix}.{feature}"
                expressions.append(expr)

    # Deduplicar
    uniq = []
    seen = set()
    for e in expressions:
        if e not in seen:
            uniq.append(e)
            seen.add(e)

    return uniq


# ------------------------------------------------------------
# Conversión Template → {feature, constraint}
# ------------------------------------------------------------

def gatekeeper_template_to_uvl(
    template_obj,
    constraint_kind_map,
    feature_dict,
    kind_map,
):
    """
    Convierte un ConstraintTemplate de Gatekeeper en:
       - feature UVL
       - constraint UVL (si se pudo extraer lógica)
    """
    meta = template_obj.get("metadata", {})
    annotations = meta.get("annotations", {}) or {}

    tmpl_name = sanitize(meta.get("name", "") or "GatekeeperTemplate")
    description = annotations.get("description", "") or annotations.get(
        "metadata.gatekeeper.sh/title", ""
    )

    # Tipo de CRD: K8sPSPPrivilegedContainer, etc.
    crd_kind = (
        template_obj.get("spec", {})
        .get("crd", {})
        .get("spec", {})
        .get("names", {})
        .get("kind", "")
    )

    # Buscar K8s kinds asociados a este template a través de constraints
    k8s_kinds = constraint_kind_map.get(crd_kind, [])
    if not k8s_kinds:
        # fallback razonable: la mayoría de PSP se aplican a Pod
        k8s_kinds = ["Pod"]

    rego_blocks = get_rego_blocks_from_template(template_obj)

    attrs = []
    if description:
        attrs.append(f"doc '{clean_description(description)}'")
    attrs.append("tool 'Gatekeeper'")
    feature_line = f"{tmpl_name} {{{', '.join(attrs)}}}"

    if not rego_blocks:
        # Sin lógica REGO detectable
        return {
            "feature": feature_line,
            "constraint": None,
        }

    exprs = build_uvl_expressions_for_template(
        tmpl_name,
        rego_blocks,
        k8s_kinds,
        feature_dict,
        kind_map,
    )

    if not exprs:
        return {
            "feature": feature_line,
            "constraint": None,
        }

    if len(exprs) == 1:
        body = exprs[0]
    else:
        body = " & ".join(exprs)

    constraint_line = f"{tmpl_name} => {body}"

    return {
        "feature": feature_line,
        "constraint": constraint_line,
    }


# ------------------------------------------------------------
# Punto de entrada: escanear todo el library de Gatekeeper
# ------------------------------------------------------------

def extract_gatekeeper_policies(root_directory: str):
    """
    Procesa un directorio con la librería de Gatekeeper (ej: 'library/')
    y devuelve una lista de:
        { "feature": "<línea UVL>", "constraint": "<línea UVL>" }
    """
    root = Path(root_directory)

    # Carga mappings desde tus CSV
    feature_dict = load_feature_dict("../resources/mapping_csv/kubernetes_mapping_properties_features.csv")
    kind_map = load_kinds_prefix_mapping("../resources/mapping_csv/kubernetes_kinds_versions_detected.csv")

    # Mapa CRDKind -> [Pod, Deployment, ...]
    constraint_kind_map = build_constraint_kind_map(root_directory)

    results = []

    for path in root.rglob("*.yaml"):
        obj = load_yaml(path)
        if not obj or not is_constraint_template(obj):
            continue

        item = gatekeeper_template_to_uvl(
            obj,
            constraint_kind_map,
            feature_dict,
            kind_map,
        )
        results.append(item)

    return results


# ------------------------------------------------------------
# Script standalone (debug / prueba)
# ------------------------------------------------------------

if __name__ == "__main__":
    # Ajusta esta ruta a tu copia local del Gatekeeper library
    library_dir = "../resources/gatekeeper-library"

    policies = extract_gatekeeper_policies(library_dir)

    print("###### RESULTADOS GATEKEEPER → UVL ######")
    for p in policies:
        print("\nFeature:")
        print(" ", p["feature"])
        if p["constraint"]:
            print("Constraint:")
            print(" ", p["constraint"])