import csv
from collections import defaultdict

import re
import yaml

def build_field_map(csv_path):
    field_map = defaultdict(list)

    with open(csv_path) as f:
        reader = csv.DictReader(f)

        for row in reader:
            # Ex: Detect feature using the FM mapping
            semantic_key = row["feature_name"]  # p.ej.: securityContext.capabilities.add // We need to take account the rest of the part of the features using the comments Kinds
            field_map[semantic_key].append(row["feature_path"])

    return field_map

def load_feature_dict(csv_file="../resources/mapping_csv/kubernetes_mapping_properties_features.csv"):
    feature_dict = {}

    with open(csv_file, newline='', encoding="utf-8") as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            midle = row["Midle"].strip()
            
            # Almacenar en el diccionario usando 'Midle' como clave
            feature_dict[midle] = row

    return feature_dict


def load_kinds_prefix_mapping(file_path: str) -> dict:
    """
    Create a dict {Kind: Prefix} from the CSV generated by mappingUvlCsvK8sOld.py
    Ex:
        {"Pod": "io_k8s_api_core_v1", "RoleBinding": "io_k8s_api_rbac_v1", ...}
    """
    mapping = {}
    with open(file_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            kind = row["Kind"].strip()
            prefix = row["Prefix"].strip()
            mapping[kind] = prefix
    return mapping


def normalize_kind_name(kind, kind_map):
    """
    Match kind string (rego: lower) to correct official K8s Kind casing.
    Ex: 'cronjob' -> 'CronJob'
    """
    ## kind_prefix_map = load_kinds_prefix_mapping("../resources/mapping_csv/kubernetes_kinds_versions_detected.csv")
    kind_lower = kind.lower()
    for k in kind_map.keys():
        if k.lower() == kind_lower:
            return k  # Return correctly capitalized e.g. CronJob
    return kind.capitalize()  # fallback


def normalize_rego_path(rego_path):
    # Eliminamos el prefijo 'container.' para que no interfiera con la búsqueda
    if rego_path.startswith("container."):
        return rego_path.replace("container.", "")
    return rego_path

def find_uvl_path_for_rego(kind, rego_path, feature_dict, kind_map): ## feature_dictç
    #print(f"Features dictss {feature_dict}")
    #kind_cap = kind.capitalize()
    real_kind = normalize_kind_name(kind, kind_map)
    #rego_key = rego_path.replace(".", "_")  # container.securityContext.capabilities.add
    rego_key = normalize_rego_path(rego_path).replace(".", "_")

    #print(f"kind    rego    {real_kind}  {rego_key}")
    # Buscar las coincidencias en el diccionario
    candidates = []

    for midle, row in feature_dict.items():
        #print(f"Midel   {midle} {row}")
        if midle.startswith(real_kind + "_") and rego_key in midle:##midle.endswith(rego_key): ## With these conds we take the last match with rego_key, the restrict of is necesary for future cases: In this cases all are similar _asString
            candidates.append(row)
            #print(f"Candidates: {candidates}")
    if not candidates:
        return None, None, None

    # Elegir la más específica (con el mayor número de coincidencias)
    best = max(candidates, key=lambda r: len(r["Midle"]))
    print(f"Value best  {best}")
    is_list = (best["Value"] == "-")

    return best["Feature"], is_list, best["Value"]


def extract_metadata_from_rego(rego_text):
    lines = rego_text.splitlines()
    capture = False
    meta_lines = []

    for line in lines:
        stripped = line.strip()

        # Start metadata
        if stripped.startswith("# METADATA"):
            capture = True
            continue

        # Stop when metadata ends
        if capture and not stripped.startswith("#"):
            break

        # Collect metadata commented lines preserving indentation
        if capture and line.lstrip().startswith("#"):
            # Find index of '#' in original line to preserve indent
            idx = line.index("#")
            yaml_part = line[idx+1:]   # drop '#' but *not* indentation after it
            meta_lines.append(yaml_part.rstrip())

    if not meta_lines:
        return {}

    # Join and remove first leading blank if present
    meta_text = "\n".join(meta_lines).lstrip("\n")

    try:
        meta_yaml = yaml.safe_load(meta_text)
        if not isinstance(meta_yaml, dict):
            return {}
    except Exception as e:
        print("YAML ERROR:", e)
        print("YAML TEXT:\n", meta_text)
        return {}

    # Handle custom nested or flattened
    custom = meta_yaml.get("custom") or {}
    print("Custom:", custom)
    if not isinstance(custom, dict):
        custom = {}

    # extract types
    kinds = []
    selectors = (
        custom.get("input", {}).get("selector", [])
        if "input" in custom
        else []
    )

    for sel in selectors:
        subtypes = sel.get("subtypes", [])
        for item in subtypes:
            if isinstance(item, dict) and "kind" in item:
                kinds.append(item["kind"].lower())

    return {
        "title": meta_yaml.get("title", ""),
        "description": meta_yaml.get("description", ""),
        "severity": custom.get("severity", ""),
        "id": custom.get("id", ""),
        "short_code": custom.get("short_code", ""),
        "recommended_action": custom.get("recommended_action", ""),
        "kinds": sorted(set(kinds)),
    }


def extract_conditions_from_rego(rego_text):
    # Example match: container.securityContext.capabilities.add[_] == "SYS_MODULE"
    pat = re.compile(r'(\S+?)\s*(==|!=)\s*"([^"]+)"')
    matches = pat.findall(rego_text)

    conditions = []
    for field, op, value in matches:
        # normalize container.securityContext.capabilities.add[_]
        field = field.replace("[_]", "")

        conditions.append({
            "field": field,
            "operator": op,
            "value": value
        })

    # Detect hostPort usage: ports[_].hostPort
    hostport_pat = re.compile(r'\bports\[_?\]\.hostPort\b|\bports\[\*\]\.hostPort\b')

    if hostport_pat.search(rego_text):
        conditions.append({
            "field": "container.ports.hostPort",
            "operator": "EXISTS",
            "value": ""  # not needed
        })

    return conditions


def parse_rego_policy(path):
    with open(path, "r") as f:
        rego = f.read()

    metadata = extract_metadata_from_rego(rego)
    conds = extract_conditions_from_rego(rego)

    return {
        "metadata": metadata,
        "conditions": conds
    }


def rego_policy_to_uvl(policy, field_map, kind_map):
    meta = policy["metadata"]
    cond = policy["conditions"][0]  # Asumimos 1 condición base por ahora

    field = cond["field"]
    operator = cond["operator"]
    value = cond["value"]

    # Convert Rego container path to canonical lookup key
    
    print(f"field key   {field}")
    field_key = normalize_rego_path(field)
    print(f"field key   {field_key}")
   # Find translation in the field map using the appropriate function
    #feature, is_list, value_field = find_uvl_path_for_rego("pod", field_key, field_map)
    

    # Feature name sanitized
    #print(f"{feature}")
    feature_name = meta["short_code"].replace("-", "_") # meta["id"] + "_" + 
    print(f"{feature_name}")
    ## To Do: clean the descriptions
    feature_block = f"""{feature_name} {{doc '{meta['description']}', severity '{meta['severity']}', tool 'OPA', recommended '{meta['recommended_action']}'}}"""
    
    constraint_parts = [] ## Added only candidate crossed
    for kind in meta["kinds"]:
        print(f"Kind    {kind}")
        feature, is_list, value_field = find_uvl_path_for_rego(kind, field_key, field_map, kind_map)
 
        if not feature:
            print(f"[WARNING] No UVL mapping for field '{field_key}' in kind '{kind}'")
            continue
        kind_cap = kind.capitalize() ### Import of objects, adjust like the generate_uvl_policies -- If 

        # Operador UVL traducido
        if operator == "==":
            expr = f"{kind_cap}.{feature} != '{value}'"
        elif operator == "!=":
            expr = f"{kind_cap}.{feature} == '{value}'"
        else:
            expr = f"UNSUPPORTED_OPERATOR({operator})"

        constraint_parts.append(expr)
    print(f"Const parts {constraint_parts}")    
    if not constraint_parts:
        print("[ERROR] No constraints generated, skipping policy")
        return None

    # Join con AND ya que todos los kinds deben cumplir la policy
    constraint = f"{feature_name} => " + " & ".join(constraint_parts)
    """if not feature:
        print(feature)
        print(f"[WARNING] No UVL mapping for field: {field_key}")
        return None"""
    
    # Buscar traducción en el CSV
    """if field_key not in field_map:
        print(f"[WARNING] No UVL mapping for field: {field_key}")
        return None
    
    #uvl_attr = field_map[field_key]
    uvl_attr = feature
    # Convert operator (only simple == banned)
    if operator == "==": ## Pod :: Prefix
        expr = f"Pod.{uvl_attr} != {value}"
    elif operator == "!=":
        expr = f"Pod.{uvl_attr} == {value}"
    else:
        expr = f"UNSUPPORTED_OPERATOR({operator})"""

    #constraint = f"{feature_name} => {expr}"
    print(f"CONSTRAINT: {constraint}")
    return feature_block, constraint



# DEMO USAGE

## ../resources/kyverno_policies_yamls
field_map = load_feature_dict("../resources/mapping_csv/kubernetes_mapping_properties_features.csv")
#data = parse_rego_policy("../resources/kyverno_policies_yamls/OPA_Policies/SYS_ADMIN_capability.rego")
data = parse_rego_policy("../resources/kyverno_policies_yamls/OPA_Policies/SYS_MODULE_capability.rego")

kind_map = load_kinds_prefix_mapping("../resources/mapping_csv/kubernetes_kinds_versions_detected.csv")

# Generate UVL feature block and constraint
feature_block, constraint = rego_policy_to_uvl(data, field_map, kind_map)

print(f"######PRUEBAS")

if feature_block and constraint:
    print("\nFeature Block:\n", feature_block)
    print("\nConstraint:\n", constraint)
else:
    print("No valid UVL mapping found.")

