import re
import json

def generate_structural_oracle(uvl_model_path, output_json_path):
    structural_dependencies = {}
    k8s_arrays = set() # NUEVO: Guardará TODO lo que sea un array
    stack = [] 

    with open(uvl_model_path, 'r', encoding='utf-8') as uvl_model:
        for raw_line in uvl_model:
            line = raw_line.strip()
            
            if not line or line.startswith("namespace") or line.startswith("imports"): continue
            if line.startswith("constraints"): break

            indent = len(raw_line.replace('\t', '    ')) - len(raw_line.replace('\t', '    ').lstrip())
            clean_line = re.sub(r'\{.*?\}', '', line).strip()
            if not clean_line: continue

            is_mandatory = (clean_line == 'mandatory')
            is_optional = (clean_line == 'optional')
            is_alternative = (clean_line == 'alternative')
            
            is_array = 'cardinality' in clean_line 
            
            feature_name = None
            data_type = None

            if not (is_mandatory or is_optional or is_alternative or clean_line == 'features'):
                parts = clean_line.split('cardinality')[0].split()
                if len(parts) > 0:
                    if parts[0] in ['String', 'Integer', 'Boolean']:
                        data_type = parts[0]
                        feature_name = parts[1] if len(parts) > 1 else None
                    else:
                        feature_name = parts[0]

                # ========================================================
                # EXTRACCIÓN GLOBAL DE ARRAYS (Ignora si es opcional/mandatory)
                # ========================================================
                if feature_name and is_array:
                    k8s_arrays.add(feature_name)

            while stack and stack[-1]['indent'] >= indent:
                stack.pop()

            current_node = {
                'indent': indent,
                'type': 'mandatory' if is_mandatory else 'optional' if is_optional else 'alternative' if is_alternative else 'feature',
                'name': feature_name,
                'data_type': data_type,
            }

            if feature_name and stack:
                parent_block = stack[-1]
                if parent_block['type'] == 'mandatory':
                    ancestor_feature = None
                    for item in reversed(stack):
                        if item['name']:
                            ancestor_feature = item['name']
                            break
                    
                    if ancestor_feature:
                        if ancestor_feature not in structural_dependencies:
                            structural_dependencies[ancestor_feature] = {}
                        
                        default_val = "autogenerated-string"
                        if "KeyMap" in feature_name: default_val = "default-key"
                        elif "ValueMap" in feature_name: default_val = "default-value"
                        elif data_type == 'Integer': default_val = 1
                        elif data_type == 'Boolean': default_val = False

                        structural_dependencies[ancestor_feature][feature_name] = default_val

            stack.append(current_node)

    # GUARDAMOS LAS DOS SECCIONES EN EL JSON
    final_output = {
        "dependencies": structural_dependencies,
        "arrays": list(k8s_arrays)
    }

    with open(output_json_path, 'w', encoding='utf-8') as f:
        json.dump(final_output, f, indent=4)
        
    print(f"✅ Oráculo generado. Dependencias: {len(structural_dependencies)}. Arrays detectados: {len(k8s_arrays)}")

# EJECUCIÓN
uvl_path = '../variability_model/policies_template/k8s/Kubernetes.uvl'
out_path = '../resources/mapping_csv/structural_oracle.json'
generate_structural_oracle(uvl_path, out_path)