apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: secure-namespace
spec:
  containers:
    - image: eu.foo.io/busybox:secure-tag@sha256:0000000000000000000000000000000000000000000000000000000000000000
      command:
        - sleep
        - "3600"
      imagePullPolicy: Always
      name: busybox
      securityContext:
        runAsUser: 10001
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
        runAsGroup: 10001
        readOnlyRootFilesystem: true
      resources:
        limits:
          cpu: 100m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 512Mi
  restartPolicy: Always
  hostNetwork: false
  dnsPolicy: ClusterFirstWithHostNet
  securityContext:
    supplementalGroups:
      - 100
    fsGroup: 2000
    runAsUser: 1000
    runAsGroup: 3000
  hostIPC: false
  hostPID: false
