apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - image: eu.foo.io/busybox:secure-tag@sha256:0000000000000000000000000000000000000000000000000000000000000000
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busybox
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          cpu: 100m
          memory: 512Mi
  restartPolicy: Always
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
